name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          add_comment: true
          labels: >
            scope: core,
            scope: api,
            scope: bot,
            scope: db,
            scope: frontend
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          add_comment: true
          labels: >
            change: feature-new,
            change: feature-update,
            change: feature-deprecate,
            change: feature-remove,
            change: bug-fix,
            change: security,
            change: performance,
            change: documentation,
            change: refactor,
            change: architecture,
            change: ci/cd,
            change: other
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          add_comment: true
          labels: >
            significance: essential,
            significance: notable,
            significance: trivial
